---
title: "Community Report: Page 1 Figures"
output: 
  html_document:
    theme: journal
---

```{r ladings, include=FALSE, warning=FALSE}
library(ggmap)
library(maps)
library(tidyverse)
library(viridis)
library(ggthemes)




#importint table w/ fips code and other info 
geo_table <- as_tibble(read.csv("C:/Users/brian/Dropbox/COCA/DATA/GMRI_aggregated data/geo_table.csv"))



raw_landings <- read.csv("C:/Users/brian/Dropbox/COCA/DATA/GMRI_aggregated data/byport_thin.csv") %>%
    left_join(., geo_table, by = "PORT_CODE") %>% drop_na(port_tidy) 

port_landings <- raw_landings %>% 
  filter(port_tidy == "PORTLAND_ME") %>% 
  na.omit() %>% 
    group_by(YEAR, port_tidy) %>% 
      summarise(
             total_value = sum(value),
             total_lbs = sum(lbs))
  

###TUFTE SPARKLINE

#taking only what we need 
landings_spark_port <- port_landings %>% dplyr::select(
  port_tidy, YEAR, total_value) %>% rename(year = YEAR)


mins_vp <- landings_spark_port %>% group_by(port_tidy) %>% mutate(min = min(total_value)) %>% 
 filter(total_value == min) %>% mutate( min = round(min, digits = 0))

max_vp <- landings_spark_port %>% group_by(port_tidy) %>% mutate(max = max(total_value)) %>% 
 filter(total_value == max) %>% mutate( max = round(max, digits = 0))

ends_p <- landings_spark_port %>% group_by(port_tidy) %>% filter(year == max(year)) %>% 
  mutate( total_value = round(total_value), digits = 0)

quarts_p <- landings_spark_port %>% group_by(port_tidy) %>% 
  summarise(
    q25 = quantile(total_value, .25),
    q75 = quantile(total_value, .75)) %>% 
      right_join(landings_spark_port)


plot.landings_min <- ggplot(data = landings_spark_port, 
       aes(year, total_value)) +
#  geom_ribbon(data = quarts_p, aes(ymin = q25, ymax = q75), fill = "grey70", alpha = .7) + 
    geom_line(size = 0.7) +
  geom_point(data = max_vp, col = 'blue') + 
  geom_point(data = mins_vp, col = 'red') + 
  geom_point(data = ends_p, col = 'black') + 
  scale_x_continuous(limits = c(1982, 2020), breaks = seq(min(landings_spark_port$year), 2015, by = 8)) +
  scale_y_continuous(labels = scales::dollar) +
  geom_text(data = mins_vp, aes(label = scales::dollar(total_value)), vjust = -1) +
  geom_text(data = max_vp, aes(label = scales::dollar(total_value)), hjust = 1.1, vjust = 0.2) + 
  geom_text(data = ends_p, aes(label = scales::dollar(total_value)), hjust = -.1, vjust = 0.1) + 
  ggtitle("Annual Landings Value",
          subtitle = "PORT OF INTEREST: 1982 - 2015") + 
    theme_tufte()  + 
      theme(axis.title = element_blank(),
            aspect.ratio = .3,
            panel.grid.major.y = element_line( size=.1, color="grey70"),
            panel.grid.major.x = element_line( size=.1, color="grey70")
            )

plot.landings_area <- ggplot(data = landings_spark_port, 
       aes(year, total_value/1000000)) +
#  geom_ribbon(data = quarts_p, aes(ymin = q25, ymax = q75), fill = "grey70", alpha = .7) + 
    geom_area(fill = "#35B779FF", alpha = .5, colour = "black", size = 1.1) +
#  geom_point(data = max_vp, col = 'blue') + 
 # geom_point(data = mins_vp, col = 'red') + 
  #geom_point(data = ends_p, col = 'black') + 
  scale_x_continuous(limits = c(1982, 2020), breaks = seq(min(landings_spark_port$year), 2015, by = 8)) +
  scale_y_continuous(labels = scales::dollar) +
  #geom_text(data = mins_vp, aes(label = scales::dollar(total_value)), vjust = -1) +
  #geom_text(data = max_vp, aes(label = scales::dollar(total_value)), hjust = 1.1, vjust = 0.2) + 
  #geom_text(data = ends_p, aes(label = scales::dollar(total_value)), hjust = -.1, vjust = 0.1) + 
  ylab("Millions of $") + 
  ggtitle("Annual Landings Value",
          subtitle = "PORT OF INTEREST: 1982 - 2015") + 
    theme_tufte() + 
      theme(axis.title.x = element_blank(),
            aspect.ratio = .3)
          


```



```{r map data, include=FALSE, warning=FALSE}
####MAP WITH FILL DATA

#read in geocoded cfders port names
geo_coded <- read.csv(
  "C:/Users/brian/Dropbox/COCA--diversity/Community data/data/data_geocoded_portnames.csv")

#create dataset for points 
coca_port_list <- geo_coded %>% 
  filter(port_tidy %in% c("STONINGTON_ME", "PORTLAND_ME", "NEWBEDFORD_MA", "POINTJUDITH_RI")) %>%
  mutate(port_nice = c("New Bedford, MA", "Point Judith, RI", "Stonington, ME", "Portland, ME"))

#importint table w/ fips code and other info 
geo_table <- as_tibble(read.csv("C:/Users/brian/Dropbox/COCA/DATA/GMRI_aggregated data/geo_table.csv"))

cfders_port_name <- read.csv(
    "C:/Users/brian/Dropbox/COCA--diversity/Community data/data/cfders_port_names.csv")

#the byport landings dataset
landings <- read.csv("C:/Users/brian/Dropbox/COCA/DATA/GMRI_aggregated data/byport_thin.csv") %>%
  left_join(., geo_table, by = "PORT_CODE") %>% 
  filter(between(YEAR, 2011,2015)) %>% na.omit(port_tidy) %>% 
  mutate(
    county_pad =  sprintf("%03d", CountyFIPS),  #inserting 0 in COUNTY
    fips_geo = as.numeric(paste0(StateFIPS,county_pad))) %>%  #joinable w/ map
  group_by(fips_geo) %>% 
  summarise(
    value = mean(value))

#reading in county fips names from ggmap
countyfipscodes <- as_tibble(maps::county.fips) %>% 
  separate(polyname, c("state", "county"), sep = ",")

#reading in cnty shapefile from ggmap
cnty <- as_tibble(map_data("county"))

#merging the fips names with the shape file (county names by county names)
map_cnty <- left_join(cnty, countyfipscodes, by = c("region" = "state", "subregion" = "county")) %>% 
  rename( gg_state = region,  gg_cnty = subregion)

#merging the cnty shapefile and fips names WITH our landings dataset,
#excluding counties w/ no landings
cnty_input_data <- left_join(map_cnty, landings, by = c("fips" = "fips_geo")) %>% 
  drop_na(value)

##state base layer shapefile, trimmed to relevant states
state_data <- as_tibble(map_data("state")) %>% 
  rename(state_group = group, state_order = order) %>% 
  filter(region %in% c("maine", "new hampshire", "massachusetts", 
                       "vermont", "rhode island", "connecticut", "new york", "new jersey",
                       "pennsylvania", "delaware", "maryland", "district of columbia", "virginia", 
                       "north carolina"))

```




```{r landings trend, echo=FALSE, warning=FALSE, include=FALSE}
map <- ggplot() +
  geom_polygon(data = state_data, aes(x=long, y=lat, group=state_group),
               alpha = .15, colour = "white")+ 
  geom_polygon(data = cnty_input_data, aes(x = long, y = lat, group = group,
                                           fill = value), alpha = .5, colour = "white") +
  geom_point(data = coca_port_list, aes(lon, lat),
             size = 2, color = "red") +
  ggrepel::geom_text_repel(data = coca_port_list, aes(x=lon, y=lat, label=port_nice),
                           direction = "both",
                           hjust = 1,
                           nudge_x = 10,
                           nudge_y = -1,
                           size = 2.7, #size of box?
                           segment.size = .3) +
  scale_fill_viridis() +
  coord_fixed(1.3, xlim = c(-77, -66.5), ylim =c(45, 40.2)) + 
  theme_map() + 
  theme(legend.position = "none")

  
```



```{r area chart, echo=FALSE, warning=FALSE, include=FALSE}
library(treemapify)
library(tidyverse)

gear_spp_input <- read.csv("C:/Users/brian/Dropbox/COCA--diversity/Community data/data/gear_spp_input.csv")


treemap <- ggplot(gear_spp_input, aes(area = value, label = spp_top,
                           subgroup = gear_type), fill = "red") + 
  geom_treemap(alpha = .4, colour = "white", fill = "#35B779FF") +
  geom_treemap_text(colour = "white", place = "center", reflow = T) +
  geom_treemap_subgroup_border(colour = "black") + 
  geom_treemap_subgroup_text(place = "topleft", alpha = 0.9, colour =
                               "black", fontface = "italic") +
    labs(fill = "Value") +
      theme_tufte()

treemap_fill <- ggplot(gear_spp_input, aes(area = value, label = spp_top,
                           subgroup = gear_type, fill =value )) + 
  geom_treemap(alpha = .65, colour = "grey70") +
  geom_treemap_text(colour = "white", place = "center", reflow = T) +
  geom_treemap_subgroup_border(colour = "white", alpha = .7) + 
  geom_treemap_subgroup_text(place = "topleft", alpha = 0.8, colour =
                               "black", fontface = "italic") +
  scale_fill_viridis(option = "magma") + 
    labs(fill = "Climate Exposure") +
  ggtitle("Climate Exposure by Gear Type and Species",
          subtitle = "Computed using 2011 - 2015 Values / Area Proportional to Value") +
      theme_tufte() + 
        theme(legend.position = "bottom")
```

```{r top 3 species data, echo=FALSE, warning=FALSE, include=FALSE }
# Brian Kennedy 
# Top 5 species Area Chart for the Community Report
# We read in raw landings data for ports
# create function that IDs top 5 ports, allows plotting of '0' values 
# outputs data files including top 5 species and total trend
# creates faceted area plot of total + top 5 species

# packages necessary 

library(tidyverse)
library(cowplot)
require(ggthemes)

# reading in 'geo' reference dataset

geo.table <- as_tibble(read.csv("C:/Users/brian/Dropbox/COCA/DATA/GMRI_aggregated data/geo_table.csv"))

# reading in raw landings data and joining with the geo dataset / need to change out to actual raw landings

raw.landings <- read.csv("C:/Users/brian/Dropbox/COCA/DATA/GMRI_aggregated data/byport_thin.csv") %>%
  left_join(., geo.table, by = "PORT_CODE") %>% drop_na(port_tidy) %>% 
    filter(YEAR > 1994) %>% 
      dplyr::select(YEAR, SPECIES, value, port_tidy) %>% 
        na.omit()


# GMRI color palettes for figures
gmri.blue <- "#00608A"  #  using external rgb calc to get hexadecimal
gmri.gray <- rgb(.233, .233, .233)



area_chart <- function(port.name, n)
# Creates input dataset for top 'x' area chart and outputs area chart
#  Args: 
#      port.name: port used to generate query    
#      n: the 'x' in top 'x'  

  {

# Filtering the raw landings dataset 
raw.landings.filter <- raw.landings %>% 
  filter(port_tidy == port.name)
  
# all species time series for the totals table
total.port <- raw.landings.filter %>% 
  group_by(port_tidy, YEAR) %>% 
    summarise(
      value = sum(value)) %>% 
        mutate(spp.names = "total") %>% 
          rename(yr.column = YEAR)
    

# table that identifies top 5 spp over the 2011 - 2015 baseline 
top.species <- raw.landings.filter %>% 
  filter(between(YEAR,2011,2015)) %>% 
  group_by(port_tidy, SPECIES) %>% 
    summarise(
      mean_value = mean(value)
    ) %>% ungroup() %>%  
  top_n(n, mean_value) %>%  
  arrange(desc(mean_value)) %>% 
    distinct(port_tidy, SPECIES)

# Dealing with top spp that do not have values in a given year by 
# creating dataframe w/ all years for every species

# creating a year column
years <- c(seq(min(raw.landings.filter$YEAR), 
               max(raw.landings.filter$YEAR), by = 1)) #vector to run through
# calling out unique names of the 'top species
spp <- unique(top.species$SPECIES)
# length of unique species 
n.spp <- length(spp)

# creating three columns of equal length

# creating column with the length years * distinct spp
yr.column <- sort(as.numeric(rep(years, n.spp))) #  note: ordering vector 
# creating a 0 row = number of years 
blank.values <- as.numeric(rep(0, length(yr.column)))
# creating column of spp names equal in length of years
spp.names <-  as.character(rep(spp, length(years)))

# binding all three columns to create our 'fake dataset' 
out <- data.frame(cbind(yr.column, blank.values, spp.names)) %>% 
  mutate(yr.column = as.numeric(as.character(yr.column)),
         blank.values = as.numeric(as.character(blank.values)))


# Landings table for top spp. note using the 'fake dataset to insert 0s where needed
top.spp.landings <- raw.landings.filter %>% 
  filter(SPECIES %in% top.species$SPECIES) %>% 
    group_by(port_tidy, YEAR, SPECIES) %>%
      full_join(out,., by = c( "yr.column" = "YEAR", "spp.names" = "SPECIES")) %>% 
        mutate_if(is.numeric, funs(ifelse(is.na(.), 0, .)))


# dataset for figure input, merging total landings row w/ top spp landings table
figure.input <-   bind_rows(top.spp.landings, total.port) %>% 
  left_join(total.port, top.spp.landings, by = c("yr.column")) %>% 
    dplyr::select(yr.column, value = value.x, total.value = value.y, 
                  spp.names = spp.names.x) %>% 
  mutate(spp.names = as.factor(spp.names))

# Changing order of plots 
figure.input$spp.names <-  fct_reorder(figure.input$spp.names, figure.input$value, mean,
                            .desc = TRUE)

# generating faceted area plot

ggplot() + 
    geom_area(data = figure.input, aes(yr.column, total.value / 1000000),
              fill = gmri.gray, alpha = .4, color = "black", size = .5)  + 
  geom_area(data = figure.input, aes(yr.column, value / 1000000),
            fill = gmri.blue, alpha = .9, color = "black", size = .5) + 
    facet_wrap(spp.names ~., nrow = 2) + 
    scale_x_continuous(breaks = c(min(yr.column), 2005, max(yr.column))) +
    ylab("Millions of $") + 
      theme_tufte() + 
      theme(aspect.ratio = .7, 
            axis.title.x = element_blank())
}      

```



```{r map, echo=FALSE, warning=FALSE}

map

```

## Landings Figures  {.tabset}

### Minimal

```{r landings_min, echo=FALSE, warning=FALSE, fig.width= 8}

plot.landings_min
```

### Area 

```{r landings_area, echo=FALSE, warning=FALSE, fig.width= 8}

plot.landings_area

```

## Top Species {.tabset}

### Stonington
```{r area stonington, echo=FALSE, warning=FALSE, fig.width= 5}

area_chart("STONINGTON_ME", 3)

```

### Portland
```{r area portland, echo=FALSE, warning=FALSE, fig.width= 5}

area_chart("PORTLAND_ME", 3)

```

### Point Judith
```{r area pj, echo=FALSE, warning=FALSE, fig.width= 5}

area_chart("POINTJUDITH_RI", 3)

```

### New Bedford 
```{r area nb, echo=FALSE, warning=FALSE, fig.width= 5}

area_chart("NEWBEDFORD_MA", 3)

```


## Port Composition {.tabset}

### No fill type

```{r treemap, echo=FALSE, warning=FALSE}

treemap

```

### Faux Vulnerability

```{r treemap_fill, echo=FALSE, warning=FALSE}

treemap_fill

```
